export const GET_EVENT_TYPE_BY_ID = 'GET_EVENT_TYPE_BY_ID';
export const GET_EVENT_TYPES = 'GET_EVENT_TYPES';
export const ADD_EVENT_TYPE = 'ADD_EVENT_TYPE';
export const EDIT_EVENT_TYPE = 'EDIT_EVENT_TYPE';
export const DELETE_EVENT_TYPE = 'DELETE_EVENT_TYPE';
