export const SET_EVENT_TYPES = 'SET_EVENT_TYPES';
export const SET_EVENT_TYPE = 'SET_EVENT_TYPE';
export const ADD_EVENT_TYPE = 'ADD_EVENT_TYPE';
export const DELETE_EVENT_TYPE = 'DELETE_EVENT_TYPE';
export const SET_EVENT_TYPE_FORM = 'SET_EVENT_TYPE_FORM';
export const SET_EVENT_TYPE_FORM_COLUMN_DISABLE =
    'SET_EVENT_TYPE_FORM_COLUMN_DISABLE';
