export const SET_EVENT_TYPES = 'SET_EVENT_TYPES';
export const SET_EVENT_TYPE = 'SET_EVENT_TYPE';
export const ADD_EVENT_TYPE = 'ADD_EVENT_TYPE';
export const DELETE_EVENT_TYPE = 'DELETE_EVENT_TYPE';
export const SET_PROPERTY = 'SET_PROPERTY';
export const CLEAR_SET_EVENT_TYPE = 'CLEAR_SET_EVENT_TYPE';
export const SET_IS_SAVED = 'SET_IS_SAVED';
