export const SET_SCHEDULED_EVENT_FILTER_VIEW =
    'SET_SCHEDULED_EVENT_FILTER_VIEW';
export const SET_SCHEDULED_EVENTS = 'SET_SCHEDULED_EVENTS';
export const FETCH_EVENT_EMAILS_FILTER = 'FETCH_EVENT_EMAILS_FILTER';
export const UPDATE_EVENT = 'UPDATE_EVENT';
