export const GET_SCHEDULED_EVENT_FILTER_VIEW =
    'GET_SCHEDULED_EVENT_FILTER_VIEW';
export const GET_SCHEDULED_EVENTS = 'GET_SCHEDULED_EVENTS';
export const GET_SCHEDULED_EVENTS_PAGINATION =
    'GET_SCHEDULED_EVENTS_PAGINATION';
export const GET_EVENT_EMAILS_FILTER = 'GET_EVENT_EMAILS_FILTER';
