export const SET_SCHEDULED_EVENT_FILTER_VIEW =
    'SET_SCHEDULED_EVENT_FILTER_VIEW';
export const SET_SCHEDULED_EVENTS = 'SET_SCHEDULED_EVENTS';
export const CLEAR_SCHEDULED_EVENTS = 'CLEAR_SCHEDULED_EVENTS';
