export const SET_SCHEDULED_EVENT_FILTER_VIEW =
    'SET_SCHEDULED_EVENT_FILTER_VIEW';
export const SET_SCHEDULED_EVENTS = 'SET_SCHEDULED_EVENTS';
export const SET_FILTER_SCHEDULED_EVENTS_TYPES = 'SET_FILTER_SCHEDULED_EVENTS_TYPES';
