export const GET_EVENT_TYPE_BY_ID_AND_NICKNAME =
    'GET_EVENT_TYPE_BY_ID_AND_NICKNAME';
export const GET_EVENT_TYPE_BY_SLUG_AND_NICKNAME =
    'GET_EVENT_TYPE_BY_SLUG_AND_NICKNAME';
export const ADD_PUBLIC_EVENT = 'ADD_PUBLIC_EVENT';
export const SET_PUBLIC_EVENT = 'SET_PUBLIC_EVENT';
export const GET_AVAILABILITIES_BY_MONTH = 'GET_AVAILABILITIES_BY_MONTH';
