export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
export const SET_INFO_NOTIFICATION = 'SET_INFO_NOTIFICATION';
export const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION';
export const REMOVE_ERROR_NOTIFICATION = 'REMOVE_ERROR_NOTIFICATION';
